version: '3'
services:
  api:
    ports:
      - "8080:80"
    #volumes:
    #  - ./PencaUcuApi:/App
    build:
      context: ./PencaUcuApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./PencaUcuApi
    #front:
    #image: <image_name>
    # Add more services as needed
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pencaucu
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
